version: '3'

services:
    ##########################
    ### SETUP SERVER CONTAINER
    ##########################
    server:
        container_name: server-prod
        # Tell docker what file to build the server from
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        environment:
            - PORT=${PORT}
            - MONGODB_URL=${MONGODB_PROD_URL}
            - SECRET=${SECRET}
            - NODE_ENV=production
        ports:
            - ${PORT}:${PORT}
        command: node server.js
        depends_on:
            - db
        restart: always
    ##########################
    ### SETUP CLIENT CONTAINER
    ##########################
    client:
        container_name: client-prod
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        links:
            - server
        restart: always
    ##########################
    ### SETUP DB CONTAINER
    ##########################
    db:
        image: mongo
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        restart: always
        volumes:
            # Map physical volume to virtual for data persistence
            # On server could be /data/db
            # For this case we will create a Docker volume and use it instead
            # You need to run docker volume create yourproject-dbdata
            - rhw2-dbdata:/data/db
# Add this to include data volume for mongo
# Confirm this is working later
volumes:
    ? rhw2-dbdata
