version: '3'

services:
    ##########################
    ### SETUP SERVER CONTAINER
    ##########################
    server:
        image: ihomenasusdevr/nrd2:server-depl
        environment:
            - PORT=${PORT}
            - MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGODB_PROD_URI}
            - SECRET=${SECRET}
            - NODE_ENV=production
        ports:
            - ${PORT}:${PORT}
        command: node server.js
        depends_on:
            - db
        restart: always
    ##########################
    ### SETUP CLIENT CONTAINER
    ##########################
    client:
        image: ihomenasusdevr/nrd2:client-depl
        ports:
            - 80:80
        links:
            - server
        restart: always
    ##########################
    ### SETUP DB CONTAINER
    ##########################
    db:
        image: mongo
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            # Map physical volume to virtual for data persistence
            # On server could be /data/db
            # For this case we will create a Docker volume and use it instead
            # You need to run docker volume create yourproject-dbdata
            - rhw2-dbdata:/data/db
            # - ./docker-scripts/:/docker-entrypoint-initdb.d
        command: [--auth]
# Add this to include data volume for mongo
# Confirm this is working later
volumes:
    rhw2-dbdata:
