# server/Dockerfile-dev

# Install node image in container
FROM node

# Install nodemon for hot reloading
RUN npm install -g nodemon

# Create and set the working directory
RUN mkdir -p /app/server
WORKDIR /app/server

# Copies the yarn.lock file to the container
# COPY yarn.lock /app/server/

# Copies the package.json to the container
COPY package*.json /app/server/
COPY package-lock.json /app/server/

# Installs the server dependencies
# RUN yarn install
RUN npm install

# Copy the server files over
COPY . /app/server/

# Command to run them
CMD ["nodemon", "server.js"]
